### ISSUE TITLE
User can delete todo item

### ISSUE THREAD

**Issue by pearllaw** [pearllaw/react-native-todo-list#3]
- [x] Create delete method
- [x] Create completed and incompleted methods to update complete todo in appstate
- [x] Create method that updates todo item when user clicks edit icon
- [x] Persist user data with asyncStorage
